### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value

### ISSUE THREAD

**Issue by szwss** [zrong/wiz2joplin#14]
# wiznote
![image](https://user-images.githubusercontent.com/584808/172220217-2167f3ac-ccf0-4001-af57-bed6cbc908ee.png)

## I used the privatization deployment of wiz

# joplin
![image](https://user-images.githubusercontent.com/584808/172220724-ae10c9c4-8f62-4826-9166-6cbbd388adce.png)

python
Python 3.10.1 (main, Dec  6 2021, 22:25:40) [Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

# use command
```
w2j -o ~/w2j -w ~/.wiznote -u user@**.com -t ***token***  -n 192.168.0.110 -p 8088 -a
```

# error

```
Please read [/Users/***user***/w2j/w2j.log] to check the conversion states.
Traceback (most recent call last):
  File "/Users/***user***/.virtualenvs/python_test/bin/w2j", line 8, in <module>
    sys.exit(main())
  File "/Users/***user***/.virtualenvs/python_test/lib/python3.10/site-packages/w2j/__init__.py", line 69, in main
    ad.sync_note_by_location(args.location, args.location_children)
  File "/Users/***user***/.virtualenvs/python_test/lib/python3.10/site-packages/w2j/adapter.py", line 577, in sync_note_by_location
    self.sync_folders()
  File "/Users/***user***/.virtualenvs/python_test/lib/python3.10/site-packages/w2j/adapter.py", line 431, in sync_folders
    jf = self.jda.post_folder(title=l2f.title)
  File "/Users/***user***/.virtualenvs/python_test/lib/python3.10/site-packages/w2j/joplin.py", line 282, in post_folder
    data = resp.json()
  File "/Users/***user***/.virtualenvs/python_test/lib/python3.10/site-packages/httpx/_models.py", line 742, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

# 修改为 python 3.9.9 报错依旧

···
...
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

···

**Comment by holoword** [comment]
wiznoteX 似乎不能离线使用了，这个库的逻辑是通过将本地文件转换到joplin中完成迁移，而没有本地文件的wiznoteX似乎没法这么做。

**Comment by zrong** [comment]
我没有在你提供的这个版本中测试过……

**Comment by webbrain-one** [comment]
Hi there! Thanks for reporting this issue. 

I've opened a PR ([#17](https://github.com/zrong/wiz2joplin/pull/17)) to fix it. The problem was that the code tried to parse the JSON response even when the Joplin API returned an empty or invalid response. The PR adds error handling to check the response status and log meaningful messages instead of crashing with a `JSONDecodeError`. This should allow the sync process to continue (or fail gracefully) instead of immediately encountering the error.

Let me know if you have any questions or need further help testing! 🚀
